/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import jssc.SerialPort;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
/**
 *
 * @author Bebe
 */
public class NewJFrame extends javax.swing.JFrame   implements SerialPortEventListener {
    static SerialPort serialPort; //Variables para el puerto serial
    static SerialPort serialPort2; //Variables para el puerto serial//
    String NoPort = new String(); //Varibale para alamcenar el nombre del puertop
    /**
     * Creates new form NewJFrameOtroEje3
     */
    public NewJFrame(String nPort) {        
        initComponents();
        AbrirPuertoSerie(nPort); //Se recibe el nombre del puerto serial elejido en el otro jFrame y se abre para la 
                                 //comunicación    
         AbrirPuertoSerie2("COM5");
    }
    /*** Método para dejar listo el puerto serial para la recepción y envío de datos ***/
private void AbrirPuertoSerie(String nPort ) {
    serialPort = new SerialPort(nPort);  // Crear el objeto 
    try {
      serialPort.openPort();//Abre el puerto serial
      serialPort.setParams(SerialPort.BAUDRATE_9600,  //Configuración del puerto serial
                           SerialPort.DATABITS_8,
                           SerialPort.STOPBITS_1,
                           SerialPort.PARITY_NONE);//Set params. Also you can set params by this string: serialPort.setParams(9600, 8, 1, 0);            
                           serialPort.addEventListener(this, SerialPort.MASK_RXCHAR);
    }        
   catch (SerialPortException ex) {
      System.out.println(ex);
    } 
}

private void AbrirPuertoSerie2(String nPort ) {
    serialPort2 = new SerialPort(nPort);  // Crear el objeto 
    try {
      serialPort2.openPort();//Abre el puerto serial
      serialPort2.setParams(SerialPort.BAUDRATE_9600,  //Configuración del puerto serial
                           SerialPort.DATABITS_8,
                           SerialPort.STOPBITS_1,
                           SerialPort.PARITY_NONE);//Set params. Also you can set params by this string: serialPort.setParams(9600, 8, 1, 0);            
                           serialPort2.addEventListener(this, SerialPort.MASK_RXCHAR);
    }        
   catch (SerialPortException ex) {
      System.out.println(ex);
    } 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("");

        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Enviar \"A\"");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar \"B\"");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/** Método para enviar el "0" por el puerto serial ***/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            serialPort.writeString("A");//Escribe el "0" en el puerto serial
            jTextArea1.append("\nSe recivio A");
        }        
        catch (SerialPortException ex) {
            System.out.println(ex);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed
/*** Método para enviar el "1" por el puerto serial ***/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try {
            serialPort.writeString("B"); //Envía el "1" por el puerto serial  
            jTextArea1.append("\nSe recivio B");
        }        
        catch (SerialPortException ex) {
            System.out.println(ex);
        }                          
    }//GEN-LAST:event_jButton2ActionPerformed
/*** Cuando se cierra el jFrame cierra tambien el puerto serial *///
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        try {
            serialPort.closePort();
        }        
        catch (SerialPortException ex) {
            System.out.println(ex);
        }         
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed
 /*** Método para detectar cuando llego un dato al puerto serial ***/
    @Override
    public void serialEvent(SerialPortEvent event) {
        if(event.isRXCHAR() && (event.getEventValue()>0)) {
            try {                
                jTextArea1.append(serialPort.readString()); // lee el dato del puerto serial y lo va agregando al jTextArea1    
             
            }
            catch (SerialPortException ex) {
                System.out.println("Error in receiving string from COM-port: " + ex);
                }
            }    
        }
        /**
         * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
  /*
     * In this class must implement the method serialEvent, through it we learn about 
     * events that happened to our port. But we will not report on all events but only 
     * those that we put in the mask. In this case the arrival of the data and change the 
     * status lines CTS and DSR
     */
        
}
